version: '3.7'

services:
  web:
    build:
      context: ./../
      dockerfile: docker/web/Dockerfile
    ports:
      - "8010:8080"
    networks:
      - web-redis
    depends_on:
      - redis
    restart: on-failure
  redis:
    build:
      context: .
      dockerfile: redis/Dockerfile
    ports:
      - "6377:6377"
    networks:
      - web-redis
    volumes:
      - "./../redis-data:/data"
    sysctls:
      net.core.somaxconn: '511'



networks:
  web-redis:
