version: '3.7'

services:
  web:
    image: windowforsun/test-spring-boot:latest
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
#      resources:
#        limits:
#          cpu: "0.1"
#          memory: 50m
    ports:
      - "8010:8080"
    networks:
      - web-redis
    depends_on:
      - redis
    restart: on-failure
  redis:
    image: windowforsun/test-redis:latest
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - "6377:6377"
    networks:
      - web-redis
    volumes:
      - "./../redis-data:/data"
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
    - "8080:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - web-redis



networks:
  web-redis:
